apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chesslink.fullname" . }}-backend-config
  namespace: chesslink
  labels:
    {{- include "chesslink.backend.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.backend.env }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}