apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-backend
  namespace: {{ .Values.namespace.default }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-backend
    spec:
      containers:
          - name: backend
            image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
            ports:
              - containerPort: {{ .Values.backend.port }}
            env:
              - name: PORT
                value: "{{ .Values.backend.port }}"
              - name: ENVIRONMENT
                value: "production"
              - name: MONGODB_URI
                value: "mongodb://{{ .Values.app.name }}-mongodb:{{ .Values.mongodb.port }}/{{ .Values.mongodb.database }}"
              - name: ALLOWED_ORIGINS
                value: "http://localhost,http://localhost:80"