apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: chesslink
  labels:
    {{- include "chesslink.mongodb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "chesslink.mongodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "chesslink.mongodb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: mongo
          image: mongo:6
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_DATABASE
              value: chesslink