apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-mongodb
  namespace: {{ .Values.namespace.default }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-mongodb
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-mongodb
    spec:
      containers:
          - name: mongodb
            image: mongo:6
            ports:
              - containerPort: {{ .Values.mongodb.port }}
            env:
              - name: MONGO_INITDB_DATABASE
                value: {{ .Values.mongodb.database }}