apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: chesslink
  labels:
    {{- include "chesslink.mongodb.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "chesslink.mongodb.selectorLabels" . | nindent 4 }}
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.service.port }}
      targetPort: mongodb
      protocol: TCP