apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-mongodb
  namespace: {{ .Values.namespace.default }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.app.name }}-mongodb
  ports:
      - port: {{ .Values.mongodb.port }}
        targetPort: {{ .Values.mongodb.port }}