app:
  name: chesslink

namespace:
  default: chesslink

mongodb:
  database: chesslink
  port: 27017
  persistence: false

backend:
  port: 8000
  image:
    repository: "029517664698.dkr.ecr.eu-north-1.amazonaws.com/chesslink/backend"
    tag: latest
  serviceType: ClusterIP

frontend:
  port: 80
  image:
    repository: "029517664698.dkr.ecr.eu-north-1.amazonaws.com/chesslink/frontend"
    tag: latest
  serviceType: LoadBalancer