apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-frontend
  namespace: {{ .Values.namespace.default }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: {{ .Values.app.name }}-frontend
  ports:
      - port: {{ .Values.frontend.port }}
        targetPort: {{ .Values.frontend.port }}