apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: chesslink
  labels:
    {{- include "chesslink.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "chesslink.backend.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http